server:
  port: 8084
  servlet:
    context-path: /evchargingstation

spring:
  datasource:
    url: jdbc:mysql://shinkansen.proxy.rlwy.net:33758/railway
    username: root
    password: vHfJPAeFUGvFYTaqGrsDTgwqAdgdzTri
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /api-docs

jwt:
  singerKey: 0a58c8b134bc3d3e7a853dc8a49bcd3895e02c20d39d29d2d976e87300dc23fa
