server:
  port: 8080
  servlet:
    context-path: /evchargingstation

spring:
  datasource:
    url: jdbc:mysql://shinkansen.proxy.rlwy.net:33758/railway
    username: root
    password: vHfJPAeFUGvFYTaqGrsDTgwqAdgdzTri
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /api-docs

jwt:
  singerKey: 0a58c8b134bc3d3e7a853dc8a49bcd3895e02c20d39d29d2d976e87300dc23fa

zalopay:
  app-id: "2554"  # Sandbox App ID
  key1: "sdngKKJmqEMzvh5QQcdD2A9XBSKUNaYn"  # Sandbox Key1
  key2: "trMrHtvjo6myautxDUiAcYsVtaeQ8nhf"  # Sandbox Key2
  endpoint: "https://sb-openapi.zalopay.vn/v2/create"  # Sandbox
  callback-url: "https://unendued-somnolent-rosemarie.ngrok-free.dev/evchargingstation/api/payment/zalopay-callback"
  redirect-url: "${app.base-url}/payment-result"

logging:
  level:
    root: INFO
    com.swp.evchargingstation: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
