server:
  forward-headers-strategy: framework
  port: 8080
  servlet:
    context-path: /evchargingstation

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 2KB

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/railway}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /api-docs

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email,profile
            redirect-uri: "https://evchargingstation.khoahtd.id.vn/evchargingstation/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

jwt:
  singerKey: ${JWT_SECRET}

# Email Configuration
mail:
  host: smtp.gmail.com
  port: 587
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  from: ${MAIL_FROM:T-Green Charging System <khoahtd14@gmail.com>}

zalopay:
  app-id: ${ZALOPAY_APP_ID}
  key1: ${ZALOPAY_KEY1}
  key2: ${ZALOPAY_KEY2}
  endpoint: "https://sb-openapi.zalopay.vn/v2/create"
  callback-url: "https://evchargingstation.khoahtd.id.vn/evchargingstation/api/webhooks/zalopay/callback"
  redirect-url: "${app.base-url}/payment-result"

# Cloudinary Configuration
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}