server:
  port: 8080
  servlet:
    context-path: /evchargingstation

spring:
  datasource:
    url: jdbc:mysql://root:NhVjxGFWNcSxFtqpTnDYScvjztjaVxpk@switchyard.proxy.rlwy.net:32406/railway
    username: root
    password: NhVjxGFWNcSxFtqpTnDYScvjztjaVxpk

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /api-docs

jwt:
  singerKey: 0a58c8b134bc3d3e7a853dc8a49bcd3895e02c20d39d29d2d976e87300dc23fa
